using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using ReflectionIT.DisposeGenerator.Attributes;
using System.Collections.Immutable;
using System.Text;

namespace ReflectionIT.DisposeGenerator;

[Generator]
public sealed class SourceGenerator : IIncrementalGenerator {

    public void Initialize(IncrementalGeneratorInitializationContext context) {

        var typeSymbols = context.SyntaxProvider.ForAttributeWithMetadataName(
                typeof(DisposableAttribute).FullName,
                predicate: static (node, cancel) => IsValidDisposableNode(node),
                transform: static (context, cancel) =>
                    new DisposableInfo(
                        (ITypeSymbol)context.SemanticModel.GetDeclaredSymbol(context.TargetNode, cancel)!,
                        (TypeDeclarationSyntax)context.TargetNode!)
            );

        var fieldsAndPropertiesSymbols = context.SyntaxProvider.ForAttributeWithMetadataName(
                typeof(DisposeAttribute).FullName,
                predicate: static (node, cancel) => IsValidDisposeNode(node),
                transform: static (context, cancel) =>
                    new DisposeInfo(context.SemanticModel.GetDeclaredSymbol(context.TargetNode, cancel)!)
            );

        var all = typeSymbols.Collect().Combine(fieldsAndPropertiesSymbols.Collect());

        context.RegisterSourceOutput(all, GenerateSource);
    }

    private void GenerateSource(SourceProductionContext context, (ImmutableArray<DisposableInfo> Left, ImmutableArray<DisposeInfo> Right) tuple) {

        var types = tuple.Left;

        if (types.IsDefaultOrEmpty || tuple.Right.IsDefaultOrEmpty) {
            return;
        }

        foreach (var dtInfo in types) {

            var fieldsOrProperties = tuple.Right.Where(d => SymbolEqualityComparer.Default.Equals(d.ContainingType, dtInfo.TypeSymbol)).ToArray();
            if (fieldsOrProperties.Length == 0) {
                continue;
            }

            CsFileBuilder builder = new CsFileBuilder();

            builder.AddAutoGeneratedHeader("ReflectionIT.DisposeGenerator")
                 .AddPreprocessorDirectives()
                 .AddEmptyLine();

            builder.AddNamespace(dtInfo.TypeSymbol.ContainingNamespace);

            builder.AddPartialType(dtInfo.TypeSymbol);
            builder.AddStatementAndStartBlock(string.Empty);

            if (!dtInfo.OverrideDispose) {

                builder.AddStatements(
                    "public void Dispose() {",
                    "    // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method",
                    "    Dispose(disposing: true);",
                    "    global::System.GC.SuppressFinalize(this);",
                    "}");
            }

            string accessModifiers = dtInfo.IsSealed || dtInfo.IsValueType ? "private" : "protected virtual";

            (string isDisposedType, string isDisposedCheck, string? setIsDisposed) = dtInfo.IsThreadSafe
                ? ("int", "global::System.Threading.Interlocked.CompareExchange(ref _isDisposed, 1, 0) == 0", null)
                : ("bool", "!_isDisposed", "_isDisposed = true;");

            string? baseDisposed = null;

            if (dtInfo.OverrideDispose) {
                accessModifiers = "protected override";
                baseDisposed = "    base.Dispose(disposing);";
            }

            builder.AddStatements(
                $"private {isDisposedType} _isDisposed;",
                $$"""{{accessModifiers}} void Dispose(bool disposing) {""",
                $$"""    if ({{isDisposedCheck}}) {""",
                "        if (disposing) {");

            foreach (var item in fieldsOrProperties) {
                builder.AddStatements($"            {item.MemberName}?.Dispose();");
            }

            builder.AddStatements("        }");

            foreach (var item in fieldsOrProperties.Where(static p => p.SetToNull)) {
                builder.AddStatements($"        {item.MemberName} = null;");
            }


            builder.AddStatements(
               $"        {setIsDisposed}",
               "    }",
               baseDisposed,
               "}");

            builder.EndPartialType(dtInfo.TypeSymbol);
            builder.EndNamespace();

            var src = builder.Build();

            var filename = dtInfo.TypeSymbol.ToDisplayString()
                              .Replace('<', '{')
                              .Replace('>', '}')
                              .Replace(" ", string.Empty);

            context.AddSource($"{filename}.g.cs", SourceText.From(src, Encoding.UTF8));
        }
    }

    internal static bool IsValidDisposableNode(SyntaxNode node) {
        // The node must be a property declaration with two accessors
        if (node is ClassDeclarationSyntax classType) {
            return classType.Modifiers.Any(SyntaxKind.PartialKeyword);
        }
        if (node is RecordDeclarationSyntax recordType) {
            return recordType.Modifiers.Any(SyntaxKind.PartialKeyword);
        }
        if (node is StructDeclarationSyntax stuctType) {
            return stuctType.Modifiers.Any(SyntaxKind.PartialKeyword);
        }
        return false;
    }

    internal static bool IsValidDisposeNode(SyntaxNode node) {
        return node is VariableDeclaratorSyntax or PropertyDeclarationSyntax;
    }

}
